package com.linplayer.tvlegacy;

import android.content.Context;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

final class MihomoConfig {
    static final int MIXED_PORT = 7890;
    static final int CONTROLLER_PORT = 9090;

    private MihomoConfig() {}

    static File baseDir(Context context) {
        return new File(context.getFilesDir(), "mihomo");
    }

    static File configFile(Context context) {
        return new File(baseDir(context), "config.yaml");
    }

    static void ensureWritten(Context context) throws IOException {
        File dir = baseDir(context);
        //noinspection ResultOfMethodCallIgnored
        dir.mkdirs();
        // Ensure providers/ exists for proxy-providers path.
        //noinspection ResultOfMethodCallIgnored
        new File(dir, "providers").mkdirs();

        String subscriptionUrl = AppPrefs.getSubscriptionUrl(context).trim();
        String yaml = subscriptionUrl.isEmpty() ? buildDirectConfig() : buildSubscriptionConfig(subscriptionUrl);
        writeUtf8Atomic(configFile(context), yaml);
    }

    private static void writeUtf8Atomic(File file, String content) throws IOException {
        File parent = file.getParentFile();
        if (parent != null) {
            //noinspection ResultOfMethodCallIgnored
            parent.mkdirs();
        }

        File tmp = new File(file.getAbsolutePath() + ".tmp");
        byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
        FileOutputStream out = null;
        try {
            out = new FileOutputStream(tmp);
            out.write(bytes);
            out.flush();
            out.getFD().sync();
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException ignored) {
                    // ignore
                }
            }
        }

        // On some Android filesystems, renameTo fails if destination exists.
        if (file.exists()) {
            //noinspection ResultOfMethodCallIgnored
            file.delete();
        }
        boolean renamed = tmp.renameTo(file);
        if (!renamed) {
            // Fallback: write directly.
            FileOutputStream out2 = null;
            try {
                out2 = new FileOutputStream(file);
                out2.write(bytes);
                out2.flush();
                out2.getFD().sync();
            } finally {
                if (out2 != null) {
                    try {
                        out2.close();
                    } catch (IOException ignored) {
                        // ignore
                    }
                }
                //noinspection ResultOfMethodCallIgnored
                tmp.delete();
            }
        }
    }

    private static String q(String value) {
        // YAML single-quoted string escaping: double single quotes.
        String v = value != null ? value : "";
        return "'" + v.replace("'", "''") + "'";
    }

    private static String buildDirectConfig() {
        return ""
                + "# lPlayerlite - mihomo config (DIRECT)\n"
                + "mode: rule\n"
                + "log-level: info\n"
                + "ipv6: false\n"
                + "\n"
                + "mixed-port: " + MIXED_PORT + "\n"
                + "socks-port: " + (MIXED_PORT + 1) + "\n"
                + "allow-lan: false\n"
                + "bind-address: 127.0.0.1\n"
                + "\n"
                + "external-controller: 127.0.0.1:" + CONTROLLER_PORT + "\n"
                + "external-ui: \"\"\n"
                + "secret: \"\"\n"
                + "\n"
                + "proxies: []\n"
                + "proxy-groups:\n"
                + "  - name: PROXY\n"
                + "    type: select\n"
                + "    proxies: [DIRECT]\n"
                + "\n"
                + "rules:\n"
                + "  - MATCH,PROXY\n";
    }

    private static String buildSubscriptionConfig(String subscriptionUrl) {
        return ""
                + "# lPlayerlite - mihomo config (subscription)\n"
                + "# Generated by app. Edits may be overwritten.\n"
                + "\n"
                + "mode: rule\n"
                + "log-level: info\n"
                + "ipv6: false\n"
                + "\n"
                + "mixed-port: " + MIXED_PORT + "\n"
                + "socks-port: " + (MIXED_PORT + 1) + "\n"
                + "allow-lan: false\n"
                + "bind-address: 127.0.0.1\n"
                + "\n"
                + "external-controller: 127.0.0.1:" + CONTROLLER_PORT + "\n"
                + "external-ui: \"\"\n"
                + "secret: \"\"\n"
                + "\n"
                + "profile:\n"
                + "  store-selected: true\n"
                + "\n"
                + "proxy-providers:\n"
                + "  sub:\n"
                + "    type: http\n"
                + "    url: " + q(subscriptionUrl) + "\n"
                + "    interval: 86400\n"
                + "    path: ./providers/sub.yaml\n"
                + "    proxy: DIRECT\n"
                + "    health-check:\n"
                + "      enable: true\n"
                + "      url: 'http://www.gstatic.com/generate_204'\n"
                + "      interval: 600\n"
                + "\n"
                + "proxy-groups:\n"
                + "  - name: AUTO\n"
                + "    type: url-test\n"
                + "    use: [sub]\n"
                + "    url: 'http://www.gstatic.com/generate_204'\n"
                + "    interval: 300\n"
                + "    tolerance: 50\n"
                + "\n"
                + "  - name: MANUAL\n"
                + "    type: select\n"
                + "    use: [sub]\n"
                + "    proxies: [DIRECT]\n"
                + "\n"
                + "  - name: PROXY\n"
                + "    type: select\n"
                + "    proxies:\n"
                + "      - AUTO\n"
                + "      - MANUAL\n"
                + "      - DIRECT\n"
                + "\n"
                + "rules:\n"
                + "  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve\n"
                + "  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve\n"
                + "  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve\n"
                + "  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve\n"
                + "  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve\n"
                + "  - MATCH,PROXY\n";
    }
}
